<template>
  <dl-button>button</dl-button>
  <dl-button
    tag="div"
    role="button"
    tabindex="0"
  >
    div
  </dl-button>
  <dl-button
    type="primary"
    tag="a"
    href="https://github.com/EricWXY/dl-element"
    target="_blank"
    rel="noopener noreferrer"
  >
    a
  </dl-button>
</template>
