/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TImageViewer: typeof import('tdesign-vue-next')['ImageViewer']

    DlSeamlessScroll: typeof import('dl-element')['DlSeamlessScroll']
  }
}
